### ISSUE TITLE
Handling of topology file errors: river segments (seg's) missing hydrologic response units (hru's)

### ISSUE THREAD

**Issue by steinadio** [UW-Hydro/bmorph#85]
I found that not all of the river segments (seg) have an hru assigned to them, (322 in the whole CRB to be exact). Each hru is assigned to a seg , but it appears that in an hru with multiple seg's, only one of the seg's is selected for the hru's data to go to. This is currently an issue when allocating conditioning data to seg's and is handled in lines 901-913 in `mizuroute_utils.py`.

There are currently 2 solutions implemented to this (when a seg is not assigned an hru) done in the following order:
1. look for seg's with an identifier closest in magnitude to the seg in question and average the data from the hru's found
2. if there are no seg's with a similar in magnitude ID (up to +/- 3), then the domain average is used as conditioning data for that seg

This creates the following issues (in same order):
1. while seg 's near each other sometimes have ID's close in magnitude, this is not a guarantee ... (for example, 101 could be at the outlet of a river while 100 is a headwater .. an extreme scenario but possible)
2. using the domain average can throw off the CDF's that are used in bmorph for conditioning by overrepresenting the average (especially in a basin like the Flathead where these hru-less seg's make up almost 13% of all the seg's). This can then be problematic for correctly applying the conditioning to locations in the basin that are at the extremes of the conditioning CDF, or potentially misclassify a seg as condition-able to the average when it should be at an extreme of the distribution

My current suggestion for a solution is to ensure that each hru has only one seg , because simply assigning each seg the hru they fall in (or sometimes multiple) can result in data being double counted. Unfortunately this does not only occur at headwaters and I do not currently see an easy way to drop these seg 's from the topology all together.

Will note that this error being in `mizuroute_utils.py` is then based in how the data is setup for bmorph, but ultimately not an error in bmorph itself ... though is one it is potentially susceptible to. I have yet to run bmorph on the data to see the impacts of handling the data in this way

**Comment by bartnijssen** [comment]
OK interesting - as you point out this is more of a topology error than a bmorph error, so my suggestion is that we fix the topology files rather than coming up with a work-around in bmorph itself (which I think is also what you are suggesting). I don’t really like either of the two suggestions for the reasons that you mention (ID is not a good metric for “closeness” and domain average is a poor estimator for local flows).

**Comment by steinadio** [comment]
okay, so for the Flathead, there are 23 segs that trigger that second fallback using the domain average, 20 of them actually just have their contributing hrus cut off when I selected out the segs for each basin (yakima, flathead, deschutes, willamette) ... while the 3 that had no contributing hrus anywhere in the CRB do have effectively zero local flows as Bart figured (1e-15 m3/s is the value they are given) ... which is maintained after mizuroute_utils.py. So I can fix the first issue by fixing the topology file subsetting and then solve the second issue via Bart's idea of passing on the segments that have effectively zero local flow

**Comment by bartnijssen** [comment]
@steinadio : I think the decision should be to skip the segments that have no associated hru rather than the segments that have effectively zero local flow. The latter follows from the former (if no contributing hru, then no local inflow), but the inverse is not true. There are perfectly valid reasons for a segment to have effectively zero local flow and in some cases we want to bias-correct for that.

Also - the decision to skip segments should be made once (not by checking flows every time step)
